### ISSUE TITLE
Cannot build clean - bind broken

### ISSUE THREAD

**Issue by rpcme** [ADLINK/meta-adlink-rockchip#1]
[log.do_configure.8972.txt](https://github.com/ADLINK/meta-adlink-rockchip/files/5058192/log.do_configure.8972.txt)

The bind build breaks after configuring per instructions:

```bash
ERROR: bind-9.11.5-P4-r0 do_configure: QA Issue: This autoconf log indicates errors, it looked at host include and/or library paths while determining system capabilities.
Rerun configure task after fixing this. [configure-unsafe]
ERROR: bind-9.11.5-P4-r0 do_configure: Fatal QA errors found, failing task.
ERROR: Logfile of failure stored in: /src/poky-ipi-smarc-rockchip/build/tmp/work/aarch64-poky-linux/bind/9.11.5-P4-r0/temp/log.do_configure.8972
ERROR: Task (/src/poky-ipi-smarc-rockchip/build/../poky/meta/recipes-connectivity/bind/bind_9.11.5-P4.bb:do_configure) failed with exit code '1'
```

I've added the log file. It looks like it's sysrooted correctly, have you seen this on your config?

**Comment by ADLINK-COM** [comment]
Hi rpcme,
   Nice to know you. 
   We followed up the building instructions yesterday and it can be successfully built as the images.
   Could  you share your steps how to generate this error? 
   

Thanks

**Comment by rpcme** [comment]
I think this is something wrong with my machine specifically. For some reason, even doing clean Poky build and adding just `bind`, these autoconf flags automatically get added:

```bash
--disable-silent-rules --disable-dependency-tracking
```
In such case, I will close this and focus on figuring out why this is happening on my machine, and then move on.
